<?php

namespace Database\Seeders;

use App\Models\AntecedenteLaboral;
use App\Models\Area;
use App\Models\Cargo;
use App\Models\Categoria;
use App\Models\Curso;
use App\Models\Documento;
use App\Models\Estudio;
use App\Models\Familiar;
use App\Models\Historialbaja;
use App\Models\Idioma;
use App\Models\Legajo;
use App\Models\Persona;
use App\Models\Titulo;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class PersonalSantiagoSeeder extends Seeder
{
    // Contraseña para TODOS los usuarios de prueba que crea este seeder.
    // Cambiarla apenas se use gente real.
    private string $passwordDemo = 'Legajo2026!';

    public function run(): void
    {
        $areaIds = Area::pluck('id', 'nombre');
        $cargoIds = Cargo::pluck('id', 'nombre');
        $categoriaIds = Categoria::pluck('id', 'nombre');

        // Usuario RRHH que figura como responsable de las bajas registradas.
        $rrhhResponsableEmail = 'silvia.paz@tribunalsgo.gob.ar';

        $personas = [
            [
                'nombre' => 'María marta Eugenia',
                'apellido' => 'Ledesma',
                'dni' => 22456700,
                'cuil' => 27224567818,
                'email' => 'mariamarta.ledesma@tribunalsgo.gob.ar',
                'genero' => 0,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1975-03-14',
                'domicilio' => 'S/N, Santiago del Estero (Capital)',
                'telefono' => '3854456700',
                'telefono_emergencia' => '3855456700',
                'rol' => 2,
                'area' => 'Secretaria General',
                'cargo' => 'Presidente/a',
                'categoria' => 'CAT 1',
                'tipo_contrato' => 0,
                'num_legajo' => 1000,
                'fecha_de_ingreso' => '2015-03-01',
                'estado' => 1,
            ],
            [
                'nombre' => 'Roberto Carlos',
                'apellido' => 'Juárez',
                'dni' => 20987654,
                'cuil' => 20209876540,
                'email' => 'roberto.juarez@tribunalsgo.gob.ar',
                'genero' => 1,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1972-11-02',
                'domicilio' => 'S/N, La Banda',
                'telefono' => '3854987654',
                'telefono_emergencia' => '3855987654',
                'rol' => 2,
                'area' => 'Fiscal General 1',
                'cargo' => 'Fiscal Jefe/a',
                'categoria' => 'CAT 1',
                'tipo_contrato' => 0,
                'num_legajo' => 1001,
                'fecha_de_ingreso' => '2015-03-01',
                'estado' => 1,
            ],
            [
                'nombre' => 'Silvia Beatriz',
                'apellido' => 'Paz',
                'dni' => 27654321,
                'cuil' => 27276543216,
                'email' => 'silvia.paz@tribunalsgo.gob.ar',
                'genero' => 0,
                'estado_civil' => 2,
                'fecha_de_nacimiento' => '1980-06-23',
                'domicilio' => 'S/N, Santiago del Estero (Capital)',
                'telefono' => '3854654321',
                'telefono_emergencia' => '3855654321',
                'rol' => 3,
                'area' => 'Personal',
                'cargo' => 'Oficial Principal de Despacho',
                'categoria' => 'CAT 5',
                'tipo_contrato' => 2,
                'num_legajo' => 1002,
                'fecha_de_ingreso' => '2015-03-01',
                'estado' => 1,
            ],
            [
                'nombre' => 'Marcelo Fabián',
                'apellido' => 'Ávila',
                'dni' => 25123456,
                'cuil' => 20251234567,
                'email' => 'marcelo.avila@tribunalsgo.gob.ar',
                'genero' => 1,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1983-01-09',
                'domicilio' => 'S/N, La Banda',
                'telefono' => '3854123456',
                'telefono_emergencia' => '3855123456',
                'rol' => 3,
                'area' => 'Personal',
                'cargo' => 'Administrativo',
                'categoria' => 'CAT 6',
                'tipo_contrato' => 2,
                'num_legajo' => 1003,
                'fecha_de_ingreso' => '2015-03-01',
                'estado' => 1,
            ],
            [
                'nombre' => 'Gabriela Noelia',
                'apellido' => 'Cardozo',
                'dni' => 30111222,
                'cuil' => 27301112225,
                'email' => 'gabriela.cardozo@tribunalsgo.gob.ar',
                'genero' => 0,
                'estado_civil' => 0,
                'fecha_de_nacimiento' => '1990-09-30',
                'domicilio' => 'S/N, Termas de Río Hondo',
                'telefono' => '3854111222',
                'telefono_emergencia' => '3855111222',
                'rol' => 3,
                'area' => 'Personal',
                'cargo' => 'Coordinador Ejecutivo',
                'categoria' => 'CAT 4',
                'tipo_contrato' => 2,
                'num_legajo' => 1004,
                'fecha_de_ingreso' => '2015-03-01',
                'estado' => 1,
            ],
            [
                'nombre' => 'Diego Alejandro',
                'apellido' => 'Herrera',
                'dni' => 28765432,
                'cuil' => 20287654325,
                'email' => 'diego.herrera@tribunalsgo.gob.ar',
                'genero' => 1,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1979-02-18',
                'domicilio' => 'S/N, Santiago del Estero (Capital)',
                'telefono' => '3854765432',
                'telefono_emergencia' => '3855765432',
                'rol' => 1,
                'area' => 'Archivo',
                'cargo' => 'Administrativo',
                'categoria' => 'CAT 6',
                'tipo_contrato' => 2,
                'num_legajo' => 1005,
                'fecha_de_ingreso' => '2010-03-01',
                'estado' => 1,
                'familiares' => [['Marta', 'Ibáñez', 33111222, 'Conyuge', '1980-04-10', 1]],
            ],
            [
                'nombre' => 'Claudia Fernanda',
                'apellido' => 'Gómez',
                'dni' => 29456129,
                'cuil' => 27294561299,
                'email' => 'claudia.gomez@tribunalsgo.gob.ar',
                'genero' => 0,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1981-07-05',
                'domicilio' => 'S/N, La Banda',
                'telefono' => '3854456129',
                'telefono_emergencia' => '3855456129',
                'rol' => 1,
                'area' => 'Auditoria',
                'cargo' => 'Operador',
                'categoria' => 'CAT 7',
                'tipo_contrato' => 2,
                'num_legajo' => 1006,
                'fecha_de_ingreso' => '2012-07-15',
                'estado' => 1,
                'estudio' => ['Universitario', 'Universidad Católica de Santiago del Estero', '2010-12-15', 'Contador/a Público/a'],
            ],
            [
                'nombre' => 'Héctor Ramón',
                'apellido' => 'Ibáñez',
                'dni' => 24678901,
                'cuil' => 20246789011,
                'email' => 'hector.ibañez@tribunalsgo.gob.ar',
                'genero' => 1,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1976-12-25',
                'domicilio' => 'S/N, Frías',
                'telefono' => '3854678901',
                'telefono_emergencia' => '3855678901',
                'rol' => 1,
                'area' => 'Comision de estudios 1',
                'cargo' => 'Ordenanza',
                'categoria' => 'CAT 8',
                'tipo_contrato' => 2,
                'num_legajo' => 1007,
                'fecha_de_ingreso' => '2015-02-10',
                'estado' => 1,
                'curso' => ['Excel Avanzado para la Gestión Pública', 'Instituto de Capacitación Provincial', '40 horas', '2023-05-20'],
            ],
            [
                'nombre' => 'Verónica Soledad',
                'apellido' => 'Barrionuevo',
                'dni' => 31234567,
                'cuil' => 27312345671,
                'email' => 'veronica.barrionuevo@tribunalsgo.gob.ar',
                'genero' => 0,
                'estado_civil' => 0,
                'fecha_de_nacimiento' => '1993-04-11',
                'domicilio' => 'S/N, Añatuya',
                'telefono' => '3854234567',
                'telefono_emergencia' => '3855234567',
                'rol' => 1,
                'area' => 'Comision de estudios 2',
                'cargo' => 'Informático',
                'categoria' => 'CAT 9',
                'tipo_contrato' => 2,
                'num_legajo' => 1008,
                'fecha_de_ingreso' => '2017-11-20',
                'estado' => 1,
                'licencia' => true,
            ],
            [
                'nombre' => 'Jorge Luis',
                'apellido' => 'Coronel',
                'dni' => 26345678,
                'cuil' => 20263456786,
                'email' => 'jorge.coronel@tribunalsgo.gob.ar',
                'genero' => 1,
                'estado_civil' => 2,
                'fecha_de_nacimiento' => '1978-10-08',
                'domicilio' => 'S/N, Santiago del Estero (Capital)',
                'telefono' => '3854345678',
                'telefono_emergencia' => '3855345678',
                'rol' => 1,
                'area' => 'Computos',
                'cargo' => 'Sección de Fiscalización',
                'categoria' => 'CAT 10',
                'tipo_contrato' => 2,
                'num_legajo' => 1009,
                'fecha_de_ingreso' => '2019-04-05',
                'estado' => 0,
                'motivo_baja' => 'Despido',
                'fecha_baja' => '2025-11-10',
            ],
            [
                'nombre' => 'Patricia Alejandra',
                'apellido' => 'Suárez',
                'dni' => 27890123,
                'cuil' => 27278901233,
                'email' => 'patricia.suarez@tribunalsgo.gob.ar',
                'genero' => 0,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1982-05-27',
                'domicilio' => 'S/N, Fernández',
                'telefono' => '3854890123',
                'telefono_emergencia' => '3855890123',
                'rol' => 1,
                'area' => 'Fiscal General 1',
                'cargo' => 'Auditoria',
                'categoria' => 'CAT 11',
                'tipo_contrato' => 2,
                'num_legajo' => 1010,
                'fecha_de_ingreso' => '2020-08-12',
                'estado' => 1,
                'idioma' => ['Inglés', 1],
            ],
            [
                'nombre' => 'Ricardo Daniel',
                'apellido' => 'Acuña',
                'dni' => 23456789,
                'cuil' => 20234567897,
                'email' => 'ricardo.acuña@tribunalsgo.gob.ar',
                'genero' => 1,
                'estado_civil' => 3,
                'fecha_de_nacimiento' => '1974-08-19',
                'domicilio' => 'S/N, Quimilí',
                'telefono' => '3854456789',
                'telefono_emergencia' => '3855456789',
                'rol' => 1,
                'area' => 'Fiscal General 2',
                'cargo' => 'Administrativo',
                'categoria' => 'CAT 12',
                'tipo_contrato' => 1,
                'num_legajo' => 1011,
                'fecha_de_ingreso' => '2021-01-25',
                'estado' => 0,
                'motivo_baja' => 'VencimientoContrato',
                'fecha_baja' => '2025-09-30',
            ],
            [
                'nombre' => 'Mónica Beatriz',
                'apellido' => 'Díaz',
                'dni' => 32109876,
                'cuil' => 27321098768,
                'email' => 'monica.diaz@tribunalsgo.gob.ar',
                'genero' => 0,
                'estado_civil' => 0,
                'fecha_de_nacimiento' => '1995-01-30',
                'domicilio' => 'S/N, La Banda',
                'telefono' => '3854109876',
                'telefono_emergencia' => '3855109876',
                'rol' => 1,
                'area' => 'Habilitación',
                'cargo' => 'Operador',
                'categoria' => 'CAT 5',
                'tipo_contrato' => 2,
                'num_legajo' => 1012,
                'fecha_de_ingreso' => '2022-06-18',
                'estado' => 1,
                'antecedente' => ['Municipalidad de La Banda', 'La Banda, Santiago del Estero', 'Administrativo', '2012-03-01', '2018-02-28', 'Renuncia'],
            ],
            [
                'nombre' => 'Sergio Damián',
                'apellido' => 'Nazur',
                'dni' => 29876543,
                'cuil' => 20298765439,
                'email' => 'sergio.nazur@tribunalsgo.gob.ar',
                'genero' => 1,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1980-03-22',
                'domicilio' => 'S/N, Santiago del Estero (Capital)',
                'telefono' => '3854876543',
                'telefono_emergencia' => '3855876543',
                'rol' => 1,
                'area' => 'Mesa de entradas',
                'cargo' => 'Ordenanza',
                'categoria' => 'CAT 6',
                'tipo_contrato' => 2,
                'num_legajo' => 1013,
                'fecha_de_ingreso' => '2023-03-09',
                'estado' => 1,
                'familiares' => [['Claudia', 'Robledo', 30222333, 'Conyuge', '1982-07-19', 1]],
            ],
            [
                'nombre' => 'Lorena Vanesa',
                'apellido' => 'Salomón',
                'dni' => 33456789,
                'cuil' => 27334567899,
                'email' => 'lorena.salomon@tribunalsgo.gob.ar',
                'genero' => 0,
                'estado_civil' => 0,
                'fecha_de_nacimiento' => '1996-11-15',
                'domicilio' => 'S/N, Monte Quemado',
                'telefono' => '3854456789',
                'telefono_emergencia' => '3855456789',
                'rol' => 1,
                'area' => 'Municipios',
                'cargo' => 'Informático',
                'categoria' => 'CAT 7',
                'tipo_contrato' => 2,
                'num_legajo' => 1014,
                'fecha_de_ingreso' => '2024-09-01',
                'estado' => 1,
            ],
            [
                'nombre' => 'Andrés Fabián',
                'apellido' => 'Taboada',
                'dni' => 25987654,
                'cuil' => 20259876541,
                'email' => 'andres.taboada@tribunalsgo.gob.ar',
                'genero' => 1,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1979-09-03',
                'domicilio' => 'S/N, Santiago del Estero (Capital)',
                'telefono' => '3854987654',
                'telefono_emergencia' => '3855987654',
                'rol' => 1,
                'area' => 'Rendición de cuentas',
                'cargo' => 'Sección de Fiscalización',
                'categoria' => 'CAT 8',
                'tipo_contrato' => 2,
                'num_legajo' => 1015,
                'fecha_de_ingreso' => '2010-03-01',
                'estado' => 1,
                'estudio' => ['Terciario', 'Instituto Superior de Formación Docente N°1', '2008-11-20', 'Técnico/a Superior en Administración Pública'],
            ],
            [
                'nombre' => 'Natalia Soledad',
                'apellido' => 'Iturre',
                'dni' => 30654321,
                'cuil' => 27306543216,
                'email' => 'natalia.iturre@tribunalsgo.gob.ar',
                'genero' => 0,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1988-06-17',
                'domicilio' => 'S/N, Suncho Corral',
                'telefono' => '3854654321',
                'telefono_emergencia' => '3855654321',
                'rol' => 1,
                'area' => 'Secretaria General',
                'cargo' => 'Auditoria',
                'categoria' => 'CAT 9',
                'tipo_contrato' => 2,
                'num_legajo' => 1016,
                'fecha_de_ingreso' => '2012-07-15',
                'estado' => 1,
                'licencia' => true,
            ],
            [
                'nombre' => 'Pablo Ezequiel',
                'apellido' => 'Gerez',
                'dni' => 34567890,
                'cuil' => 20345678906,
                'email' => 'pablo.gerez@tribunalsgo.gob.ar',
                'genero' => 1,
                'estado_civil' => 0,
                'fecha_de_nacimiento' => '1997-02-28',
                'domicilio' => 'S/N, La Banda',
                'telefono' => '3854567890',
                'telefono_emergencia' => '3855567890',
                'rol' => 1,
                'area' => 'Servicios Generales',
                'cargo' => 'Administrativo',
                'categoria' => 'CAT 10',
                'tipo_contrato' => 1,
                'num_legajo' => 1017,
                'fecha_de_ingreso' => '2015-02-10',
                'estado' => 1,
                'curso' => ['Atención al Público y Mesa de Entradas', 'Instituto de Capacitación Provincial', '20 horas', '2022-08-14'],
            ],
            [
                'nombre' => 'Carla Estefanía',
                'apellido' => 'Farías',
                'dni' => 31987654,
                'cuil' => 27319876540,
                'email' => 'carla.farias@tribunalsgo.gob.ar',
                'genero' => 0,
                'estado_civil' => 0,
                'fecha_de_nacimiento' => '1994-12-09',
                'domicilio' => 'S/N, Loreto',
                'telefono' => '3854987654',
                'telefono_emergencia' => '3855987654',
                'rol' => 1,
                'area' => 'Archivo',
                'cargo' => 'Operador',
                'categoria' => 'CAT 11',
                'tipo_contrato' => 2,
                'num_legajo' => 1018,
                'fecha_de_ingreso' => '2017-11-20',
                'estado' => 1,
                'familiares' => [['Tomás', 'Farías', null, 'Hijos', '2015-09-03', 1]],
            ],
            [
                'nombre' => 'Emanuel Nicolás',
                'apellido' => 'Corbalán',
                'dni' => 35678901,
                'cuil' => 20356789017,
                'email' => 'emanuel.corbalan@tribunalsgo.gob.ar',
                'genero' => 1,
                'estado_civil' => 0,
                'fecha_de_nacimiento' => '1998-07-21',
                'domicilio' => 'S/N, Santiago del Estero (Capital)',
                'telefono' => '3854678901',
                'telefono_emergencia' => '3855678901',
                'rol' => 1,
                'area' => 'Auditoria',
                'cargo' => 'Ordenanza',
                'categoria' => 'CAT 12',
                'tipo_contrato' => 1,
                'num_legajo' => 1019,
                'fecha_de_ingreso' => '2019-04-05',
                'estado' => 1,
                'idioma' => ['Inglés', 0],
            ],
            [
                'nombre' => 'Yolanda del Valle',
                'apellido' => 'Romano',
                'dni' => 22987321,
                'cuil' => 27229873216,
                'email' => 'yolanda.romano@tribunalsgo.gob.ar',
                'genero' => 0,
                'estado_civil' => 3,
                'fecha_de_nacimiento' => '1973-04-06',
                'domicilio' => 'S/N, Clodomira',
                'telefono' => '3854987321',
                'telefono_emergencia' => '3855987321',
                'rol' => 1,
                'area' => 'Comision de estudios 1',
                'cargo' => 'Informático',
                'categoria' => 'CAT 5',
                'tipo_contrato' => 2,
                'num_legajo' => 1020,
                'fecha_de_ingreso' => '2020-08-12',
                'estado' => 0,
                'motivo_baja' => 'Renuncia',
                'fecha_baja' => '2025-06-15',
            ],
            [
                'nombre' => 'Walter Ariel',
                'apellido' => 'Frías',
                'dni' => 27456912,
                'cuil' => 20274569124,
                'email' => 'walter.frias@tribunalsgo.gob.ar',
                'genero' => 1,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1981-10-14',
                'domicilio' => 'S/N, Beltrán',
                'telefono' => '3854456912',
                'telefono_emergencia' => '3855456912',
                'rol' => 1,
                'area' => 'Comision de estudios 2',
                'cargo' => 'Sección de Fiscalización',
                'categoria' => 'CAT 6',
                'tipo_contrato' => 2,
                'num_legajo' => 1021,
                'fecha_de_ingreso' => '2021-01-25',
                'estado' => 1,
                'familiares' => [['Elsa', 'Toledo', 15333444, 'Padres', '1950-02-14', 1]],
            ],
            [
                'nombre' => 'Rosa Mabel',
                'apellido' => 'Ibarra',
                'dni' => 24123890,
                'cuil' => 27241238909,
                'email' => 'rosa.ibarra@tribunalsgo.gob.ar',
                'genero' => 0,
                'estado_civil' => 2,
                'fecha_de_nacimiento' => '1977-05-02',
                'domicilio' => 'S/N, Santiago del Estero (Capital)',
                'telefono' => '3854123890',
                'telefono_emergencia' => '3855123890',
                'rol' => 1,
                'area' => 'Computos',
                'cargo' => 'Auditoria',
                'categoria' => 'CAT 7',
                'tipo_contrato' => 2,
                'num_legajo' => 1022,
                'fecha_de_ingreso' => '2022-06-18',
                'estado' => 0,
                'motivo_baja' => 'Traslado',
                'fecha_baja' => '2025-03-01',
            ],
            [
                'nombre' => 'Julio César',
                'apellido' => 'Sayago',
                'dni' => 28234561,
                'cuil' => 20282345618,
                'email' => 'julio.sayago@tribunalsgo.gob.ar',
                'genero' => 1,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1979-08-28',
                'domicilio' => 'S/N, La Banda',
                'telefono' => '3854234561',
                'telefono_emergencia' => '3855234561',
                'rol' => 1,
                'area' => 'Fiscal General 1',
                'cargo' => 'Administrativo',
                'categoria' => 'CAT 8',
                'tipo_contrato' => 2,
                'num_legajo' => 1023,
                'fecha_de_ingreso' => '2023-03-09',
                'estado' => 1,
                'antecedente' => ['Correo Argentino', 'Santiago del Estero (Capital)', 'Cadete', '2010-01-15', '2016-12-20', 'Fin de contrato'],
            ],
            [
                'nombre' => 'Estela Marina',
                'apellido' => 'Ledesma',
                'dni' => 26789012,
                'cuil' => 27267890124,
                'email' => 'estela.ledesma@tribunalsgo.gob.ar',
                'genero' => 0,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1978-03-19',
                'domicilio' => 'S/N, Forres',
                'telefono' => '3854789012',
                'telefono_emergencia' => '3855789012',
                'rol' => 1,
                'area' => 'Fiscal General 2',
                'cargo' => 'Operador',
                'categoria' => 'CAT 9',
                'tipo_contrato' => 2,
                'num_legajo' => 1024,
                'fecha_de_ingreso' => '2024-09-01',
                'estado' => 1,
                'licencia' => true,
            ],
            [
                'nombre' => 'Fabián Osvaldo',
                'apellido' => 'Juárez',
                'dni' => 29123045,
                'cuil' => 20291230459,
                'email' => 'fabian.juarez@tribunalsgo.gob.ar',
                'genero' => 1,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1982-01-11',
                'domicilio' => 'S/N, Termas de Río Hondo',
                'telefono' => '3854123045',
                'telefono_emergencia' => '3855123045',
                'rol' => 1,
                'area' => 'Habilitación',
                'cargo' => 'Ordenanza',
                'categoria' => 'CAT 10',
                'tipo_contrato' => 2,
                'num_legajo' => 1025,
                'fecha_de_ingreso' => '2010-03-01',
                'estado' => 1,
                'familiares' => [['Analía', 'Moreno', 27888999, 'Conyuge', '1984-05-22', 1], ['Bruno', 'Juárez', null, 'Hijos', '2012-08-30', 1], ['Mía', 'Juárez', null, 'Hijos', '2016-03-11', 1]],
            ],
            [
                'nombre' => 'Marisa Alejandra',
                'apellido' => 'Paz',
                'dni' => 30987012,
                'cuil' => 27309870129,
                'email' => 'marisa.paz@tribunalsgo.gob.ar',
                'genero' => 0,
                'estado_civil' => 0,
                'fecha_de_nacimiento' => '1990-09-25',
                'domicilio' => 'S/N, Santiago del Estero (Capital)',
                'telefono' => '3854987012',
                'telefono_emergencia' => '3855987012',
                'rol' => 1,
                'area' => 'Mesa de entradas',
                'cargo' => 'Informático',
                'categoria' => 'CAT 11',
                'tipo_contrato' => 2,
                'num_legajo' => 1026,
                'fecha_de_ingreso' => '2012-07-15',
                'estado' => 1,
                'estudio' => ['Universitario', 'Universidad Nacional de Santiago del Estero', '2015-07-10', 'Abogado/a'],
            ],
            [
                'nombre' => 'Nicolás Ezequiel',
                'apellido' => 'Ávila',
                'dni' => 36123456,
                'cuil' => 20361234562,
                'email' => 'nicolas.avila@tribunalsgo.gob.ar',
                'genero' => 1,
                'estado_civil' => 0,
                'fecha_de_nacimiento' => '1999-06-30',
                'domicilio' => 'S/N, Colonia Dora',
                'telefono' => '3854123456',
                'telefono_emergencia' => '3855123456',
                'rol' => 1,
                'area' => 'Municipios',
                'cargo' => 'Sección de Fiscalización',
                'categoria' => 'CAT 12',
                'tipo_contrato' => 2,
                'num_legajo' => 1027,
                'fecha_de_ingreso' => '2015-02-10',
                'estado' => 1,
                'licencia' => true,
            ],
            [
                'nombre' => 'Cynthia Paola',
                'apellido' => 'Cardozo',
                'dni' => 32456098,
                'cuil' => 27324560985,
                'email' => 'cynthia.cardozo@tribunalsgo.gob.ar',
                'genero' => 0,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1993-02-14',
                'domicilio' => 'S/N, La Banda',
                'telefono' => '3854456098',
                'telefono_emergencia' => '3855456098',
                'rol' => 1,
                'area' => 'Rendición de cuentas',
                'cargo' => 'Auditoria',
                'categoria' => 'CAT 5',
                'tipo_contrato' => 2,
                'num_legajo' => 1028,
                'fecha_de_ingreso' => '2017-11-20',
                'estado' => 1,
                'curso' => ['Gestión Digital de Legajos', 'Instituto de Capacitación Provincial', '30 horas', '2024-02-10'],
            ],
            [
                'nombre' => 'Ramón Alberto',
                'apellido' => 'Herrera',
                'dni' => 21345678,
                'cuil' => 20213456785,
                'email' => 'ramon.herrera@tribunalsgo.gob.ar',
                'genero' => 1,
                'estado_civil' => 1,
                'fecha_de_nacimiento' => '1969-12-01',
                'domicilio' => 'S/N, Santiago del Estero (Capital)',
                'telefono' => '3854345678',
                'telefono_emergencia' => '3855345678',
                'rol' => 1,
                'area' => 'Secretaria General',
                'cargo' => 'Administrativo',
                'categoria' => 'CAT 6',
                'tipo_contrato' => 2,
                'num_legajo' => 1029,
                'fecha_de_ingreso' => '2019-04-05',
                'estado' => 0,
                'motivo_baja' => 'Jubilacion',
                'fecha_baja' => '2025-12-31',
            ],
        ];


        foreach ($personas as $datos) {
            $persona = Persona::create([
                'nombre' => $datos['nombre'],
                'apellido' => $datos['apellido'],
                'dni' => $datos['dni'],
                'cuil' => $datos['cuil'],
                'email' => $datos['email'],
                'genero' => $datos['genero'],
                'estado_civil' => $datos['estado_civil'],
                'fecha_de_nacimiento' => $datos['fecha_de_nacimiento'],
                'domicilio' => $datos['domicilio'],
                'telefono' => $datos['telefono'],
                'telefono_emergencia' => $datos['telefono_emergencia'],
            ]);

            User::create([
                'name' => $datos['nombre'] . ' ' . $datos['apellido'],
                'email' => $datos['email'],
                'password' => Hash::make($this->passwordDemo),
                'rol' => $datos['rol'],
                'email_verified_at' => now(),
                'persona_id' => $persona->id,
            ]);

            $legajo = Legajo::create([
                'num_legajo' => $datos['num_legajo'],
                'estado' => $datos['estado'],
                'fecha_de_ingreso' => $datos['fecha_de_ingreso'],
                'tipo_contrato' => $datos['tipo_contrato'],
                'persona_id' => $persona->id,
                'categoria_id' => $categoriaIds[$datos['categoria']],
                'cargo_id' => $cargoIds[$datos['cargo']],
                'area_id' => $areaIds[$datos['area']],
            ]);

            if ($datos['estado'] === 0) {
                $motivos = [
                    'Renuncia' => 0,
                    'Despido' => 1,
                    'VencimientoContrato' => 2,
                    'Jubilacion' => 3,
                    'Fallecimiento' => 4,
                    'Incapacidad' => 5,
                    'Traslado' => 6,
                ];

                $rrhh = User::where('email', $rrhhResponsableEmail)->first();

                Historialbaja::create([
                    'legajo_id' => $legajo->id,
                    'user_id' => $rrhh?->id ?? 1,
                    'motivo' => $motivos[$datos['motivo_baja']],
                    'fecha_baja' => $datos['fecha_baja'],
                ]);
            }

            if (!empty($datos['licencia'])) {
                Documento::create([
                    'descripcion' => 'Licencia solicitada por ' . $datos['nombre'] . ' ' . $datos['apellido'],
                    'tipodoc' => 3,
                    'activo' => true,
                    'legajo_id' => $legajo->id,
                ]);
            }

            if (!empty($datos['estudio'])) {
                [$nivelNombre, $institucion, $fechaFin, $tituloNombre] = $datos['estudio'];

                $niveles = [
                    'SinEstudio' => 0, 'Primario_No' => 1, 'Primario' => 2,
                    'Secundario_No' => 3, 'Secundario' => 4, 'Terciario_No' => 5,
                    'Terciario' => 6, 'Universitario' => 7, 'Doctorado' => 8, 'Maestria' => 9,
                ];

                $estudio = Estudio::create([
                    'institucion' => $institucion,
                    'nivel_estudio' => $niveles[$nivelNombre],
                    'fecha_fin' => $fechaFin,
                    'persona_id' => $persona->id,
                ]);

                Titulo::create([
                    'nombre' => $tituloNombre,
                    'estudio_id' => $estudio->id,
                ]);
            }

            if (!empty($datos['curso'])) {
                [$nombreCurso, $institucionCurso, $duracion, $fechaCurso] = $datos['curso'];

                Curso::create([
                    'persona_id' => $persona->id,
                    'nombre' => $nombreCurso,
                    'institucion' => $institucionCurso,
                    'duracion' => $duracion,
                    'fecha' => $fechaCurso,
                    'tiene_certificado' => true,
                ]);
            }

            if (!empty($datos['idioma'])) {
                [$idiomaNombre, $nivelIdioma] = $datos['idioma'];

                Idioma::create([
                    'persona_id' => $persona->id,
                    'idioma' => $idiomaNombre,
                    'nivel' => $nivelIdioma,
                ]);
            }

            if (!empty($datos['antecedente'])) {
                [$empleador, $lugar, $cargoAnterior, $fechaInicio, $fechaFinAnt, $motivoEgreso] = $datos['antecedente'];

                AntecedenteLaboral::create([
                    'persona_id' => $persona->id,
                    'empleador' => $empleador,
                    'lugar_de_trabajo' => $lugar,
                    'cargo' => $cargoAnterior,
                    'fecha_inicio' => $fechaInicio,
                    'fecha_fin' => $fechaFinAnt,
                    'motivo_egreso' => $motivoEgreso,
                ]);
            }

            if (!empty($datos['familiares'])) {
                $parentescos = [
                    'Conyuge' => 0, 'Padres' => 1, 'Hijos' => 2, 'Sobrinos' => 3, 'Suegros' => 4,
                ];

                foreach ($datos['familiares'] as $familiar) {
                    [$nombreFam, $apellidoFam, $dniFam, $parentescoNombre, $fechaNacFam, $viveFam] = $familiar;

                    Familiar::create([
                        'nombre' => $nombreFam,
                        'apellido' => $apellidoFam,
                        'dni' => $dniFam,
                        'fecha_de_nacimiento' => $fechaNacFam,
                        'parentesco' => $parentescos[$parentescoNombre],
                        'vive' => $viveFam,
                        'persona_id' => $persona->id,
                    ]);
                }
            }
        }
    }
}
