# Generated by Django 4.2.11 on 2026-04-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_legajo', models.CharField(max_length=50, unique=True, verbose_name='Número de Legajo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('dni', models.CharField(max_length=16, verbose_name='DNI')),
                ('cargo', models.CharField(max_length=30, verbose_name='Cargo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(null=True, verbose_name='creada')),
                ('update_date', models.DateTimeField(null=True, verbose_name='actualizada')),
            ],
            options={
                'verbose_name': 'Legajo',
                'verbose_name_plural': 'Legajos',
            },
        ),
    ]
